Addressed Serokells comments
tqtezos/minter-sdk pull request #172
Opened 2021-06-01 17:47 UTC by EGuenz

2021-06-03 12:57 UTC, dcastro commented on packages/minter-contracts/ligo/src/english_auction/english_auction_fa2.mligo
>        then ([%Michelson ({| { FAILWITH } |} : string * (nat * nat * address * timestamp * timestamp) -> unit)] ("Invalid Bid amount", (auction.current_bid, token_amount, auction.highest_bidder, aucti
Forgot to change `Invalid Bid amount` -> `INVALID_BID_AMOUNT` here.

2021-06-04 14:27 UTC, dcastro requested changes
Thanks for addressing our points!

The only one left is [this test](https://github.com/tqtezos/minter-sdk/pull/165/checks?check_run_id=2746262571#step:8:445) that's still failing.

This PR introduces a new requirement, `min_raise` and `min_raise_percent` cannot both be zero. But the issue remains: if one of them is zero, then a user can outbid the previous user by placing the exact same bid, without raising.

2021-06-04 14:27 UTC, dcastro commented on packages/minter-contracts/ligo/src/english_auction/README.md
> +A new bid can be placed if the following confitions are met:
```suggestion
A new bid can be placed if the following conditions are met: 
```

2021-06-04 14:27 UTC, dcastro commented on packages/minter-contracts/ligo/src/english_auction/README.md
> +In this version of the NFT English Auction contract, bids are made in some FA2 token specified at contract origination as `bid_currency`. Bidders must add the auction contract as an operator for thei
```suggestion
In this version of the NFT English Auction contract, bids are made in some FA2 token specified at contract origination as `bid_currency`. Bidders must add the auction contract as an operator for their bid token and then specify the amount they would like to bid in the set FA2 token (`bid_currency`) as an argument to the `bid` entrypoint. The entrypoint will fail if the auction cannot transfer the indicated amount of `bid_currency` to itself from the bidder. In this version of the contract, no tez can be transferred to any entrypoint. An attempt to do so will fail with `DONT_TRANSFER_TEZ_TO_ANY_ENTRYPOINT`. 
```

2021-06-04 14:27 UTC, dcastro commented on packages/minter-contracts/ligo/src/english_auction/README.md
> +- An auction is considered to be `ended` if either the current time is greater than or equal to the end time of the auction or round time has passed after the last bid was placed.
```suggestion
- An auction is considered to be `ended` if either the current time is greater than or equal to the end time of the auction or `round_time` has passed after the last bid was placed. 
```

2021-06-04 14:27 UTC, dcastro commented on packages/minter-contracts/ligo/src/english_auction/README.md
> +- An auction is considered to have `started` if the current time is greater than the auctions start time.
```suggestion
- An auction is considered to have `started` if the current time is greater than or equal to the auction's start time.
```

2021-06-04 16:13 UTC, EGuenz commented
> Thanks for addressing our points!
> 
> The only one left is [this test](https://github.com/tqtezos/minter-sdk/pull/165/checks?check_run_id=2746262571#step:8:445) that's still failing.
> 
> This PR introduces a new requirement, `min_raise` and `min_raise_percent` cannot both be zero. But the issue remains: if one of them is zero, then a user can outbid the previous user by placing the exact same bid, without raising.

Thanks! The last commit should have just fixed that. I keep forgetting that the condition is a new bid has to satisfy `min_raise` OR `min_raise_percent` conditions-- not their conjunction.

2021-06-08 16:36 UTC, dcastro approved these changes
All the tests in #165 are passing now! :+1:

2021-06-08 20:56 UTC, merged